[package]
name = "zlambda-scheduler"
version = "0.0.0"
authors = [ "Justus Flerlage <justus@sutsuj.com>" ]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
zlambda-core = { path = "../zlambda-core" }

[lib]
crate-type   = ["rlib", "cdylib"]
