[package]
name = "zlambda-realtime-task"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
zlambda-core = { path = "../zlambda-core" }

[lib]
crate-type = ["rlib", "cdylib"]
