[package]
name = "zlambda-common"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
libloading = "0.7"
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
