[package]
name = "zlambda-wasm-matrix"
version = "0.1.0"
authors = ["Justus Flerlage <justus@sutsuj.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
