[package]
name = "zlambda-matrix-process"
version = "0.0.0"
edition = "2021"

[dependencies]
bytes = "*"
byteorder = { version = "*", features = [ "i128" ] }
zlambda-matrix = { path = "../zlambda-matrix" }
