[package]
name = "zlambda-wasm"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "*"
wasmer = { version = "4", features = [ "llvm" ], default-features = false }
wasmer-compiler-llvm = "4"
zlambda-core = { path = "../zlambda-core" }
zlambda-matrix = { path = "../zlambda-matrix" }
