[package]
name = "zlambda-client"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
zlambda-common = { path = "../zlambda-common" }
