[package]
name = "zlambda-client"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio-util = { version = "0", features = ["full"] }
tokio-stream  = { version = "0", features = ["net"] }
tokio = { version = "1", features = ["full"] }
zlambda-common = { path = "../zlambda-common" }
