[package]
name = "zlambda-process"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["process"] }
zlambda-core = { path = "../zlambda-core" }
